# default profile

# Spring
spring:
  profiles:
    include:
      - httpclient
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  # swagger issue
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQLDialect
  threads:
    virtual:
      enabled: false

# Server
server:
  port: 8080
  tomcat:
    threads:
      max: 100
      min-spare: 50
    accept-count: 50
    connection-timeout: 30000
    uri-encoding: UTF-8
  forward-headers-strategy: framework

# Swagger
springdoc:
  api-docs:
    enabled: true   # openApi 문서 활성화
  swagger-ui:
    enabled: true   # UI 활성화
  override-with-generic-response: false  # 일반화된 응답 사용 여부

# Encrypt
encrypt:
  key: 1sk5s012fl5ldmzz
  algorithm: AES/CBC/PKCS5Padding

# Auth
auth:
  jwt:
    secret: 077d202b70b3e9b84a9cdfa93c8e4e014dd0f407a0f08b43c771eae9b5fda89ece275c9ea9ab6a501882622bcf529dc7c3602e247d7a6709c71ad63abffe6a54
    issuer: oops-api
    audience: oops-api
    access-exp: 10800      # 3시간
    refresh-exp: 7776000   # 90일

# OAuth
oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
    redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/api/v1/oauth/google/callback}
